apiVersion: v2
name: platform-grafana
description: Grafana — Dashboards, Goal-oriented Monitoring & Feedback Interface
type: application
version: 0.1.0
appVersion: "11.0.0"
keywords:
  - iso42001
  - platform
  - monitoring
home: https://github.com/CIGIP-UPV/MLOps-ISO42001-K3s-Catalog
sources:
  - https://github.com/CIGIP-UPV/MLOps-ISO42001-K3s-Catalog
maintainers:
  - name: CIGIP-UPV
dependencies:
  - name: grafana
    version: "~8"
    repository: "https://grafana.github.io/helm-charts"
