apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-evidently
  labels:
    {{- include "platform-evidently.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "platform-evidently.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform-evidently.labels" . | nindent 8 }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.metrics.port }}"
        prometheus.io/path: "/metrics"
      {{- end }}
    spec:
      containers:
        - name: evidently
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          volumeMounts:
            - name: workspace
              mountPath: /workspace
            - name: config
              mountPath: /etc/evidently
          env:
            - name: WORKSPACE_PATH
              value: /workspace
            - name: CONFIG_PATH
              value: /etc/evidently/workspace.json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 20
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-evidently-config
        - name: workspace
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-evidently-workspace
          {{- else }}
          emptyDir: {}
          {{- end }}
