# =============================================================================
# Evidently UI Service
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-evidently.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-evidently.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "platform-evidently.selectorLabels" . | nindent 4 }}
