apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opcua-gateway
  labels:
    {{- include "edge-opc-ua-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
  selector:
    {{- include "edge-opc-ua-gateway.selectorLabels" . | nindent 4 }}
