apiVersion: v2
name: platform-training-jobs
description: Training Jobs — Scheduled Model Retraining
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - iso42001
  - platform
  - ai-lifecycle
home: https://github.com/CIGIP-UPV/MLOps-ISO42001-K3s-Catalog
sources:
  - https://github.com/CIGIP-UPV/MLOps-ISO42001-K3s-Catalog
maintainers:
  - name: CIGIP-UPV
