apiVersion: v2
name: platform-minio
description: MinIO — S3-Compatible Object Storage
type: application
version: 0.1.0
appVersion: "5.0"
keywords:
  - iso42001
  - platform
  - data-management
home: https://github.com/CIGIP-UPV/MLOps-ISO42001-K3s-Catalog
sources:
  - https://github.com/CIGIP-UPV/MLOps-ISO42001-K3s-Catalog
maintainers:
  - name: CIGIP-UPV
dependencies:
  - name: minio
    version: "~5"
    repository: "https://charts.min.io/"
