#!/usr/bin/env python3
"""
iso42001-postrender.py: Helm post-renderer that stamps the ISO/IEC 42001
traceability labels on every rendered resource and pod template.

Some upstream charts wrapped by the catalog do not expose a hook to add
labels to every object they render (for example the MLflow chart has no pod
labels). install.sh therefore runs every release through this post-renderer
so that ``kubectl get ... -l iso42001=true`` finds the whole deployment.

The labels come from the managed ``iso42001Labels`` block of the chart
values.yaml (generated by publish.py from CHART_META). The chart folder is
given in the ISO42001_CHART_DIR environment variable.

Usage (as done by install.sh):
    ISO42001_CHART_DIR=catalog/edge/storage/postgresql/manifests \\
      helm upgrade --install ... --post-renderer infrastructure/iso42001-postrender.py
"""

import os
import pathlib
import sys

import yaml

POD_TEMPLATE_KINDS = {"Deployment", "StatefulSet", "DaemonSet", "Job", "ReplicaSet"}


def load_labels() -> dict:
    chart_dir = os.environ.get("ISO42001_CHART_DIR")
    if not chart_dir:
        sys.exit("iso42001-postrender: ISO42001_CHART_DIR is not set")
    values = yaml.safe_load((pathlib.Path(chart_dir) / "values.yaml").read_text(encoding="utf-8")) or {}
    labels = values.get("iso42001Labels")
    if not isinstance(labels, dict) or not labels:
        sys.exit(f"iso42001-postrender: no iso42001Labels block in {chart_dir}/values.yaml")
    return {str(k): str(v) for k, v in labels.items()}


def stamp(meta_holder: dict, labels: dict) -> None:
    md = meta_holder.setdefault("metadata", {}) or {}
    meta_holder["metadata"] = md
    md["labels"] = {**(md.get("labels") or {}), **labels}


def label_doc(doc: dict, labels: dict) -> None:
    if doc.get("kind", "").endswith("List") and isinstance(doc.get("items"), list):
        for item in doc["items"]:
            if isinstance(item, dict):
                label_doc(item, labels)
        return
    stamp(doc, labels)
    kind, spec = doc.get("kind"), doc.get("spec")
    if not isinstance(spec, dict):
        return
    if kind in POD_TEMPLATE_KINDS and isinstance(spec.get("template"), dict):
        stamp(spec["template"], labels)
    elif kind == "CronJob" and isinstance(spec.get("jobTemplate"), dict):
        stamp(spec["jobTemplate"], labels)
        job_spec = spec["jobTemplate"].get("spec") or {}
        if isinstance(job_spec.get("template"), dict):
            stamp(job_spec["template"], labels)
    elif kind in ("Prometheus", "Alertmanager", "PrometheusAgent"):
        pm = spec.setdefault("podMetadata", {}) or {}
        spec["podMetadata"] = pm
        pm["labels"] = {**(pm.get("labels") or {}), **labels}


def main() -> int:
    labels = load_labels()
    docs = list(yaml.safe_load_all(sys.stdin))
    out = []
    for doc in docs:
        if isinstance(doc, dict) and doc.get("kind"):
            label_doc(doc, labels)
        if doc is not None:
            out.append(doc)
    yaml.safe_dump_all(out, sys.stdout, sort_keys=False, default_flow_style=False, width=1000)
    return 0


if __name__ == "__main__":
    sys.exit(main())
